# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7035a3bd989c6d99201ce3213033b5d4adb67db085375a89ff6c1092254a434b63fe978c7116f2f40f4c70fb89c0301ed01aa6b565f5b30137debf3fe603d07d

test:
  secret_key_base: b0658f69025c0682eb7816b1fe77a20c85fc84029ee82f7d050b0802735da31eae025d82e1a262f9ea6a48e523ad2d615e67ad21718d2a98c615fb489f9dea97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
